# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UrFhCkrXK0VjgL0i7-vP6KKPNU4TLv-S
"""

import streamlit as st
import pandas as pd
import numpy as np
import os
from joblib import load

# --------------------------------------------------
# PAGE CONFIG
# --------------------------------------------------
st.set_page_config(
    page_title="Bank Churn Prediction",
    layout="centered"
)

st.title("🏦 Bank Customer Churn Prediction")
st.markdown("Industrial ML system to predict customer churn risk")

# --------------------------------------------------
# LOAD TRAINED MODEL (SAFE FOR STREAMLIT CLOUD)
# --------------------------------------------------
MODEL_PATH = os.path.join(os.path.dirname(__file__), "churn_pipeline.pkl")
model = load(MODEL_PATH)

# --------------------------------------------------
# SIDEBAR INPUTS (RAW FEATURES)
# --------------------------------------------------
st.sidebar.header("Customer Information")

CreditScore = st.sidebar.number_input("Credit Score", 300, 900, 650)
Geography = st.sidebar.selectbox("Geography", ["France", "Spain", "Germany"])
Gender = st.sidebar.selectbox("Gender", ["Male", "Female"])
Age = st.sidebar.number_input("Age", 18, 80, 35)
Tenure = st.sidebar.slider("Tenure (Years)", 0, 10, 3)
Balance = st.sidebar.number_input("Account Balance", 0.0, 300000.0, 50000.0)
NumOfProducts = st.sidebar.selectbox("Number of Products", [1, 2, 3, 4])
HasCrCard = st.sidebar.selectbox("Has Credit Card", [0, 1])
IsActiveMember = st.sidebar.selectbox("Is Active Member", [0, 1])
EstimatedSalary = st.sidebar.number_input("Estimated Salary", 10000.0, 200000.0, 60000.0)

# --------------------------------------------------
# CREATE BASE DATAFRAME
# --------------------------------------------------
input_df = pd.DataFrame([{
    "CreditScore": CreditScore,
    "Geography": Geography,
    "Gender": Gender,
    "Age": Age,
    "Tenure": Tenure,
    "Balance": Balance,
    "NumOfProducts": NumOfProducts,
    "HasCrCard": HasCrCard,
    "IsActiveMember": IsActiveMember,
    "EstimatedSalary": EstimatedSalary
}])

# --------------------------------------------------
# FEATURE ENGINEERING (MUST MATCH TRAINING)
# --------------------------------------------------

# Ratio features
input_df["Balance_to_Salary_ratio"] = (
    input_df["Balance"] / (input_df["EstimatedSalary"] + 1)
)

input_df["Is_Zero_Balance"] = (input_df["Balance"] == 0).astype(int)

input_df["Products_per_year"] = (
    input_df["NumOfProducts"] / (input_df["Tenure"] + 1)
)

# Business logic features
HIGH_VALUE_BALANCE_THRESHOLD = 75000
input_df["High_value_customer"] = (
    input_df["Balance"] > HIGH_VALUE_BALANCE_THRESHOLD
).astype(int)

input_df["Inactive_High_Balance"] = (
    (input_df["IsActiveMember"] == 0) &
    (input_df["High_value_customer"] == 1)
).astype(int)

# Bucketing features
input_df["Age_Bucket"] = pd.cut(
    input_df["Age"],
    bins=[0, 30, 45, 60, 100],
    labels=["Young", "Mid", "Senior", "Very_Senior"]
)

input_df["Tenure_Bucket"] = pd.cut(
    input_df["Tenure"],
    bins=[-1, 2, 5, 10],
    labels=["New", "Medium", "Loyal"]
)

# --------------------------------------------------
# PREDICTION
# --------------------------------------------------
st.markdown("---")

if st.button("🔮 Predict Churn"):

    churn_prob = model.predict_proba(input_df)[0][1]

    st.subheader(f"📊 Churn Probability: **{churn_prob:.2%}**")

    # Risk segmentation
    if churn_prob >= 0.60:
        st.error("🚨 HIGH RISK CUSTOMER")
        st.markdown("**Action:** Immediate retention offer & RM call")

    elif churn_prob >= 0.30:
        st.warning("⚠️ MEDIUM RISK CUSTOMER")
        st.markdown("**Action:** Promotional offer / loyalty benefits")

    else:
        st.success("✅ LOW RISK CUSTOMER")
        st.markdown("**Action:** No immediate action required")

    # Business explainability
    st.markdown("### 🧠 Key Risk Indicators")
    if IsActiveMember == 0:
        st.write("- Customer is inactive")
    if Balance == 0:
        st.write("- Zero account balance")
    if NumOfProducts == 1:
        st.write("- Uses only one product")
    if Tenure <= 2:
        st.write("- Low tenure customer")